/**
 * TypeScript type definitions for Wails desktop app bindings.
 * These are auto-generated by Wails from the Go struct methods.
 */
declare global {
  interface Window {
    go?: {
      main?: {
        WailsApp?: {
          GetAPIPort(): Promise<string>
          GetAPIURL(): Promise<string>
          GetVersion(): Promise<string>
          GetDataDir(): Promise<string>
          OpenExternalURL(url: string): Promise<void>
          MinimizeToTray(): Promise<void>
          ShowWindow(): Promise<void>
          SetMinimizeToTray(enable: boolean): Promise<void>
          GetMinimizeToTray(): Promise<boolean>
          ShowNotification(title: string, message: string): Promise<void>
          SetAutoStart(enable: boolean): Promise<void>
          IsAutoStartEnabled(): Promise<boolean>
        }
      }
    }
    /** Wails v2 runtime — injected automatically in Wails builds */
    runtime?: {
      EventsOn(event: string, callback: (...data: any[]) => void): void
      EventsOff(event: string): void
      EventsEmit(event: string, ...data: any[]): void
      BrowserOpenURL(url: string): void
      WindowMinimise(): void
      WindowShow(): void
      WindowHide(): void
    }
  }
}

export {}
